version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - scraper
    environment:
      - MONGO_URI=mongodb://mongo:27017/projekt

  scraper:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
    container_name: scraper
    depends_on:
      - mongo
    ports:
      - "5001:5001"

volumes:
  mongo-data:
